import type { SearchContentApiResponse } from './campaign-api';

export const MOCK_CAMPAIGN_DATA: SearchContentApiResponse = {
	location: {
		cityCode: 'NEW_YORK',
		cityName: 'New York',
		countryCode: 'US',
		countryName: 'United States',
	},
	banner: {
		title: 'Best of New York',
		description: 'Iconic experiences across the city that never sleeps',
		images: [
			'https://cdn-imgix.headout.com/media/images/77534adf-721a-48fa-87e1-f17e25d187b8-1750999333752-288170.jpg',
		],
	},
	themeColor: '#1A1A2E',
	meta: {},
	priceData: {},
	cities: [],
	error: null,
	tourGroups: [
		{
			id: 35853,
			displayName:
				'Hudson Yards Guided Walking Tour with Edge Observation Deck Tickets',
			language: 'EN',
			urlSlug:
				'/edge-observation-deck-tickets/hudson-yards-walking-tour-with-edge-ticket-e-35853/',
			ratings: { count: 0, value: 0.0 },
			descriptors: [
				{
					code: 'DURATION',
					name: 'Duration',
					displayName: 'Duration',
					iconUrl:
						'https://cdn-imgix.headout.com/assets/svg/descriptors/clock.svg',
					description: '2 hrs 30 mins',
					type: 'STANDARD',
				},
				{
					code: 'FREE_CANCELLATION',
					name: 'Free Cancellation',
					displayName: 'Free cancellation',
					iconUrl:
						'https://cdn-imgix.headout.com/assets/svg/descriptors/cancellation.svg',
					description:
						'Free cancellation up to 24 hours before the start of your experience',
					type: 'STANDARD',
				},
				{
					code: 'BOOK_NOW_PAY_LATER',
					name: 'Book now, pay later',
					displayName: 'Book now, pay later',
					iconUrl:
						'https://cdn-imgix.headout.com/assets/svg/descriptors/bnpl.svg',
					description: 'Book now without paying anything.',
					type: 'STANDARD',
				},
			],
			medias: [
				{
					url: 'https://cdn-imgix.headout.com/media/images/7a51efca-e364-42e2-93a7-21fa3f4a5fc9-1750998492973-288153.jpg',
					type: 'IMAGE',
					metadata: {
						altText:
							'High Line in New York with skyscrapers and autumn foliage.',
						videoDuration: undefined,
						uploadDate: '2025-06-27',
					},
				},
				{
					url: 'https://cdn-imgix.headout.com/media/images/0ba057f0-25e5-4e98-ba34-16f54d352ae9-1750998456514-288148.jpg',
					type: 'IMAGE',
					metadata: {
						altText:
							'Guests posing during Hudson Yards walking tour.',
						videoDuration: undefined,
						uploadDate: '2025-06-27',
					},
				},
			],
			listingPrice: {
				currencyCode: 'USD',
				originalPrice: 79.0,
				finalPrice: 79.0,
				minimumPayablePrice: 79.0,
				type: 'PER_PERSON',
				otherPricesExist: true,
				bestDiscount: 0,
				cashbackValue: 0,
				cashbackType: 'PERCENTAGE',
				tourId: 75928,
			},
			primaryCollection: { id: 4012, displayName: 'Edge NYC' },
			primaryCategory: { id: 2, displayName: 'Tours' },
			primarySubCategory: { id: 1009, displayName: 'Walking Tours' },
			primaryCity: { code: 'NEW_YORK', displayName: 'New York' },
			combo: false,
			multiVariant: false,
			flowType: 'NORMAL',
			schedule: undefined,
			personas: [],
			itineraries: [],
			content: undefined,
			minDuration: 9000000,
			maxDuration: 9000000,
			guestCount: undefined,
			source: undefined,
		},
		{
			id: 27662,
			displayName: 'New York Lunch Cruise',
			language: 'EN',
			urlSlug: '/lunch-cruises/new-york-bateaux-lunch-cruise-e-27662/',
			ratings: { count: 4200, value: 4.6 },
			descriptors: [
				{
					code: 'DURATION',
					name: 'Duration',
					displayName: 'Duration',
					iconUrl:
						'https://cdn-imgix.headout.com/assets/svg/descriptors/clock.svg',
					description: '2 hrs',
					type: 'STANDARD',
				},
				{
					code: 'FREE_CANCELLATION',
					name: 'Free Cancellation',
					displayName: 'Free cancellation',
					iconUrl:
						'https://cdn-imgix.headout.com/assets/svg/descriptors/cancellation.svg',
					description: 'Free cancellation up to 24 hours before',
					type: 'STANDARD',
				},
				{
					code: 'MEALS_INCLUDED',
					name: 'Meals Included',
					displayName: 'Meals included',
					iconUrl:
						'https://cdn-imgix.headout.com/assets/svg/descriptors/foodanddrink.svg',
					description: 'Indulge in a sumptuous meal',
					type: 'INCLUSION_BASED',
				},
			],
			medias: [
				{
					url: 'https://cdn-imgix.headout.com/media/images/95c7a14aba1ff507585be8eb4a2a6ab3-27662-new-york-bateaux-new-york-premier-lunch-cruise-01.jpg',
					type: 'IMAGE',
					metadata: {
						altText: 'Cruise ship with passengers on deck.',
						videoDuration: undefined,
						uploadDate: '2024-06-12',
					},
				},
				{
					url: 'https://cdn-imgix.headout.com/media/images/d9864400ccb3fff6f2963e1bca34225e-27662-new-york-bateaux-new-york-premier-lunch-cruise-09.jpg',
					type: 'IMAGE',
					metadata: {
						altText: 'Dining setup with NYC skyline view.',
						videoDuration: undefined,
						uploadDate: '2024-06-12',
					},
				},
			],
			listingPrice: {
				currencyCode: 'USD',
				originalPrice: 139.0,
				finalPrice: 115.0,
				minimumPayablePrice: 115.0,
				type: 'PER_PERSON',
				otherPricesExist: false,
				bestDiscount: 17,
				cashbackValue: 0,
				cashbackType: 'PERCENTAGE',
				tourId: 27662,
			},
			primaryCollection: { id: 502, displayName: 'New York Cruises' },
			primaryCategory: { id: 5, displayName: 'Experiences' },
			primarySubCategory: { id: 2001, displayName: 'Cruises' },
			primaryCity: { code: 'NEW_YORK', displayName: 'New York' },
			combo: false,
			multiVariant: false,
			flowType: 'NORMAL',
			schedule: undefined,
			personas: [],
			itineraries: [],
			content: undefined,
			minDuration: 7200000,
			maxDuration: 7200000,
			guestCount: undefined,
			source: undefined,
		},
		{
			id: 14987,
			displayName:
				'Empire State Building Observation Deck: Express Tickets',
			language: 'EN',
			urlSlug: '/empire-state-building-tickets/express-e-14987/',
			ratings: { count: 38500, value: 4.5 },
			descriptors: [
				{
					code: 'DURATION',
					name: 'Duration',
					displayName: 'Duration',
					iconUrl:
						'https://cdn-imgix.headout.com/assets/svg/descriptors/clock.svg',
					description: 'Flexible',
					type: 'STANDARD',
				},
				{
					code: 'SKIP_THE_LINE',
					name: 'Skip the line',
					displayName: 'Skip the line',
					iconUrl:
						'https://cdn-imgix.headout.com/assets/svg/descriptors/skiptheline.svg',
					description: 'Skip the regular queue',
					type: 'STANDARD',
				},
			],
			medias: [
				{
					url: 'https://cdn-imgix.headout.com/media/images/93b8dab2-a2d6-4c06-80c4-ae355e5914ed-1750998462735-288152.jpg',
					type: 'IMAGE',
					metadata: {
						altText: 'Empire State Building observation deck.',
						videoDuration: undefined,
						uploadDate: '2025-06-27',
					},
				},
			],
			listingPrice: {
				currencyCode: 'USD',
				originalPrice: 58.0,
				finalPrice: 58.0,
				minimumPayablePrice: 58.0,
				type: 'PER_PERSON',
				otherPricesExist: true,
				bestDiscount: 0,
				cashbackValue: 0,
				cashbackType: 'PERCENTAGE',
				tourId: 14987,
			},
			primaryCollection: {
				id: 301,
				displayName: 'Empire State Building',
			},
			primaryCategory: { id: 1, displayName: 'Tickets' },
			primarySubCategory: { id: 101, displayName: 'Observation Decks' },
			primaryCity: { code: 'NEW_YORK', displayName: 'New York' },
			combo: false,
			multiVariant: true,
			flowType: 'NORMAL',
			schedule: undefined,
			personas: [],
			itineraries: [],
			content: undefined,
			minDuration: undefined,
			maxDuration: undefined,
			guestCount: undefined,
			source: undefined,
		},
		{
			id: 3228,
			displayName:
				'Statue of Liberty & Ellis Island Ferry Tickets with Audio Tour',
			language: 'EN',
			urlSlug: '/statue-of-liberty-tickets/ferry-tickets-e-3228/',
			ratings: { count: 21000, value: 4.4 },
			descriptors: [
				{
					code: 'DURATION',
					name: 'Duration',
					displayName: 'Duration',
					iconUrl:
						'https://cdn-imgix.headout.com/assets/svg/descriptors/clock.svg',
					description: '3-4 hrs',
					type: 'STANDARD',
				},
				{
					code: 'AUDIO_GUIDE',
					name: 'Audio Guide',
					displayName: 'Audio guide',
					iconUrl:
						'https://cdn-imgix.headout.com/assets/svg/descriptors/audioguide.svg',
					description: 'Self-guided audio tour included',
					type: 'INCLUSION_BASED',
				},
			],
			medias: [
				{
					url: 'https://cdn-imgix.headout.com/media/images/45870489-c377-41ee-8008-dbe72ad9278b-1750998461237-288150.jpg',
					type: 'IMAGE',
					metadata: {
						altText: 'Statue of Liberty from the water.',
						videoDuration: undefined,
						uploadDate: '2025-06-27',
					},
				},
			],
			listingPrice: {
				currencyCode: 'USD',
				originalPrice: 29.0,
				finalPrice: 24.0,
				minimumPayablePrice: 24.0,
				type: 'PER_PERSON',
				otherPricesExist: false,
				bestDiscount: 17,
				cashbackValue: 0,
				cashbackType: 'PERCENTAGE',
				tourId: 3228,
			},
			primaryCollection: { id: 202, displayName: 'Statue of Liberty' },
			primaryCategory: { id: 1, displayName: 'Tickets' },
			primarySubCategory: { id: 102, displayName: 'Ferry Tickets' },
			primaryCity: { code: 'NEW_YORK', displayName: 'New York' },
			combo: false,
			multiVariant: false,
			flowType: 'NORMAL',
			schedule: undefined,
			personas: [],
			itineraries: [],
			content: undefined,
			minDuration: 10800000,
			maxDuration: 14400000,
			guestCount: undefined,
			source: undefined,
		},
		{
			id: 9812,
			displayName: 'Top of the Rock Observation Deck Tickets',
			language: 'EN',
			urlSlug: '/top-of-the-rock-tickets/e-9812/',
			ratings: { count: 15600, value: 4.6 },
			descriptors: [
				{
					code: 'DURATION',
					name: 'Duration',
					displayName: 'Duration',
					iconUrl:
						'https://cdn-imgix.headout.com/assets/svg/descriptors/clock.svg',
					description: 'Flexible',
					type: 'STANDARD',
				},
			],
			medias: [
				{
					url: 'https://cdn-imgix.headout.com/media/images/4ff69cd8-caec-4a74-a6a4-4c49735479d8-1750998490160-288155.jpg',
					type: 'IMAGE',
					metadata: {
						altText: 'Manhattan from Top of the Rock.',
						videoDuration: undefined,
						uploadDate: '2025-06-27',
					},
				},
			],
			listingPrice: {
				currencyCode: 'USD',
				originalPrice: 40.0,
				finalPrice: 40.0,
				minimumPayablePrice: 40.0,
				type: 'PER_PERSON',
				otherPricesExist: true,
				bestDiscount: 0,
				cashbackValue: 0,
				cashbackType: 'PERCENTAGE',
				tourId: 9812,
			},
			primaryCollection: { id: 401, displayName: 'Top of the Rock' },
			primaryCategory: { id: 1, displayName: 'Tickets' },
			primarySubCategory: { id: 101, displayName: 'Observation Decks' },
			primaryCity: { code: 'NEW_YORK', displayName: 'New York' },
			combo: false,
			multiVariant: true,
			flowType: 'NORMAL',
			schedule: undefined,
			personas: [],
			itineraries: [],
			content: undefined,
			minDuration: undefined,
			maxDuration: undefined,
			guestCount: undefined,
			source: undefined,
		},
		{
			id: 19043,
			displayName: 'Central Park Bike Rental',
			language: 'EN',
			urlSlug: '/central-park-bike-rental/e-19043/',
			ratings: { count: 8200, value: 4.7 },
			descriptors: [
				{
					code: 'DURATION',
					name: 'Duration',
					displayName: 'Duration',
					iconUrl:
						'https://cdn-imgix.headout.com/assets/svg/descriptors/clock.svg',
					description: 'Flexible',
					type: 'STANDARD',
				},
				{
					code: 'FREE_CANCELLATION',
					name: 'Free Cancellation',
					displayName: 'Free cancellation',
					iconUrl:
						'https://cdn-imgix.headout.com/assets/svg/descriptors/cancellation.svg',
					description: 'Free cancellation up to 24 hours before',
					type: 'STANDARD',
				},
			],
			medias: [
				{
					url: 'https://cdn-imgix.headout.com/media/images/77534adf-721a-48fa-87e1-f17e25d187b8-1750999333752-288170.jpg',
					type: 'IMAGE',
					metadata: {
						altText: 'Cyclists in Central Park, New York.',
						videoDuration: undefined,
						uploadDate: '2025-06-27',
					},
				},
			],
			listingPrice: {
				currencyCode: 'USD',
				originalPrice: 15.0,
				finalPrice: 15.0,
				minimumPayablePrice: 15.0,
				type: 'PER_PERSON',
				otherPricesExist: true,
				bestDiscount: 0,
				cashbackValue: 0,
				cashbackType: 'PERCENTAGE',
				tourId: 19043,
			},
			primaryCollection: { id: 601, displayName: 'Central Park' },
			primaryCategory: { id: 5, displayName: 'Experiences' },
			primarySubCategory: { id: 3001, displayName: 'Bike Rentals' },
			primaryCity: { code: 'NEW_YORK', displayName: 'New York' },
			combo: false,
			multiVariant: false,
			flowType: 'NORMAL',
			schedule: undefined,
			personas: [],
			itineraries: [],
			content: undefined,
			minDuration: undefined,
			maxDuration: undefined,
			guestCount: undefined,
			source: undefined,
		},
		{
			id: 11203,
			displayName: 'NYC: Helicopter Tour of Manhattan',
			language: 'EN',
			urlSlug: '/helicopter-tours/new-york-helicopter-tour-e-11203/',
			ratings: { count: 6800, value: 4.8 },
			descriptors: [
				{
					code: 'DURATION',
					name: 'Duration',
					displayName: 'Duration',
					iconUrl:
						'https://cdn-imgix.headout.com/assets/svg/descriptors/clock.svg',
					description: '12-15 mins',
					type: 'STANDARD',
				},
				{
					code: 'SMALL_GROUP',
					name: 'Small Group',
					displayName: 'Small group',
					iconUrl:
						'https://cdn-imgix.headout.com/assets/svg/descriptors/smallgroup.svg',
					description: 'Max 6 people',
					type: 'STANDARD',
				},
			],
			medias: [
				{
					url: 'https://cdn-imgix.headout.com/media/images/0ba057f0-25e5-4e98-ba34-16f54d352ae9-1750998456514-288148.jpg',
					type: 'IMAGE',
					metadata: {
						altText: 'Aerial view of Manhattan from helicopter.',
						videoDuration: undefined,
						uploadDate: '2023-05-01',
					},
				},
			],
			listingPrice: {
				currencyCode: 'USD',
				originalPrice: 264.0,
				finalPrice: 219.0,
				minimumPayablePrice: 219.0,
				type: 'PER_PERSON',
				otherPricesExist: false,
				bestDiscount: 17,
				cashbackValue: 0,
				cashbackType: 'PERCENTAGE',
				tourId: 11203,
			},
			primaryCollection: { id: 701, displayName: 'NYC Helicopter Tours' },
			primaryCategory: { id: 5, displayName: 'Experiences' },
			primarySubCategory: { id: 4001, displayName: 'Helicopter Tours' },
			primaryCity: { code: 'NEW_YORK', displayName: 'New York' },
			combo: false,
			multiVariant: false,
			flowType: 'NORMAL',
			schedule: undefined,
			personas: [],
			itineraries: [],
			content: undefined,
			minDuration: 720000,
			maxDuration: 900000,
			guestCount: undefined,
			source: undefined,
		},
		{
			id: 8821,
			displayName: 'The SUMMIT One Vanderbilt: Observation Experience',
			language: 'EN',
			urlSlug: '/summit-one-vanderbilt/tickets-e-8821/',
			ratings: { count: 11200, value: 4.7 },
			descriptors: [
				{
					code: 'DURATION',
					name: 'Duration',
					displayName: 'Duration',
					iconUrl:
						'https://cdn-imgix.headout.com/assets/svg/descriptors/clock.svg',
					description: 'Flexible',
					type: 'STANDARD',
				},
				{
					code: 'SKIP_THE_LINE',
					name: 'Skip the line',
					displayName: 'Skip the line',
					iconUrl:
						'https://cdn-imgix.headout.com/assets/svg/descriptors/skiptheline.svg',
					description: 'Skip the regular queue',
					type: 'STANDARD',
				},
			],
			medias: [
				{
					url: 'https://cdn-imgix.headout.com/media/images/93b8dab2-a2d6-4c06-80c4-ae355e5914ed-1750998462735-288152.jpg',
					type: 'IMAGE',
					metadata: {
						altText:
							'SUMMIT One Vanderbilt observation deck interior.',
						videoDuration: undefined,
						uploadDate: '2023-07-01',
					},
				},
			],
			listingPrice: {
				currencyCode: 'USD',
				originalPrice: 49.0,
				finalPrice: 39.0,
				minimumPayablePrice: 39.0,
				type: 'PER_PERSON',
				otherPricesExist: true,
				bestDiscount: 20,
				cashbackValue: 0,
				cashbackType: 'PERCENTAGE',
				tourId: 8821,
			},
			primaryCollection: { id: 801, displayName: 'One Vanderbilt' },
			primaryCategory: { id: 1, displayName: 'Tickets' },
			primarySubCategory: { id: 101, displayName: 'Observation Decks' },
			primaryCity: { code: 'NEW_YORK', displayName: 'New York' },
			combo: false,
			multiVariant: true,
			flowType: 'NORMAL',
			schedule: undefined,
			personas: [],
			itineraries: [],
			content: undefined,
			minDuration: undefined,
			maxDuration: undefined,
			guestCount: undefined,
			source: undefined,
		},
		{
			id: 22451,
			displayName: 'Broadway Show: The Lion King Tickets',
			language: 'EN',
			urlSlug: '/broadway/lion-king-tickets-e-22451/',
			ratings: { count: 29400, value: 4.9 },
			descriptors: [
				{
					code: 'DURATION',
					name: 'Duration',
					displayName: 'Duration',
					iconUrl:
						'https://cdn-imgix.headout.com/assets/svg/descriptors/clock.svg',
					description: '2 hrs 30 mins',
					type: 'STANDARD',
				},
			],
			medias: [
				{
					url: 'https://cdn-imgix.headout.com/media/images/45870489-c377-41ee-8008-dbe72ad9278b-1750998461237-288150.jpg',
					type: 'IMAGE',
					metadata: {
						altText:
							'The Lion King Broadway musical stage performance.',
						videoDuration: undefined,
						uploadDate: '2023-08-01',
					},
				},
			],
			listingPrice: {
				currencyCode: 'USD',
				originalPrice: 149.0,
				finalPrice: 149.0,
				minimumPayablePrice: 149.0,
				type: 'PER_PERSON',
				otherPricesExist: true,
				bestDiscount: 0,
				cashbackValue: 0,
				cashbackType: 'PERCENTAGE',
				tourId: 22451,
			},
			primaryCollection: { id: 901, displayName: 'Broadway Shows' },
			primaryCategory: { id: 3, displayName: 'Shows' },
			primarySubCategory: { id: 5001, displayName: 'Broadway' },
			primaryCity: { code: 'NEW_YORK', displayName: 'New York' },
			combo: false,
			multiVariant: true,
			flowType: 'NORMAL',
			schedule: undefined,
			personas: [],
			itineraries: [],
			content: undefined,
			minDuration: 9000000,
			maxDuration: 9000000,
			guestCount: undefined,
			source: undefined,
		},
		{
			id: 5517,
			displayName:
				'NYC: High Line & Hudson Yards Self-Guided Walking Tour',
			language: 'EN',
			urlSlug: '/walking-tours/high-line-hudson-yards-e-5517/',
			ratings: { count: 3900, value: 4.5 },
			descriptors: [
				{
					code: 'DURATION',
					name: 'Duration',
					displayName: 'Duration',
					iconUrl:
						'https://cdn-imgix.headout.com/assets/svg/descriptors/clock.svg',
					description: '1-2 hrs',
					type: 'STANDARD',
				},
				{
					code: 'FREE_CANCELLATION',
					name: 'Free Cancellation',
					displayName: 'Free cancellation',
					iconUrl:
						'https://cdn-imgix.headout.com/assets/svg/descriptors/cancellation.svg',
					description: 'Free cancellation up to 24 hours before',
					type: 'STANDARD',
				},
			],
			medias: [
				{
					url: 'https://cdn-imgix.headout.com/media/images/77534adf-721a-48fa-87e1-f17e25d187b8-1750999333752-288170.jpg',
					type: 'IMAGE',
					metadata: {
						altText: 'High Line elevated park in NYC.',
						videoDuration: undefined,
						uploadDate: '2023-09-01',
					},
				},
			],
			listingPrice: {
				currencyCode: 'USD',
				originalPrice: 12.0,
				finalPrice: 12.0,
				minimumPayablePrice: 12.0,
				type: 'PER_PERSON',
				otherPricesExist: false,
				bestDiscount: 0,
				cashbackValue: 0,
				cashbackType: 'PERCENTAGE',
				tourId: 5517,
			},
			primaryCollection: { id: 1001, displayName: 'High Line' },
			primaryCategory: { id: 2, displayName: 'Tours' },
			primarySubCategory: { id: 1009, displayName: 'Walking Tours' },
			primaryCity: { code: 'NEW_YORK', displayName: 'New York' },
			combo: false,
			multiVariant: false,
			flowType: 'NORMAL',
			schedule: undefined,
			personas: [],
			itineraries: [],
			content: undefined,
			minDuration: 3600000,
			maxDuration: 7200000,
			guestCount: undefined,
			source: undefined,
		},
		{
			id: 31088,
			displayName:
				'Combo: Empire State Building + Top of the Rock Tickets',
			language: 'EN',
			urlSlug: '/combo/empire-state-top-rock-e-31088/',
			ratings: { count: 7600, value: 4.6 },
			descriptors: [
				{
					code: 'DURATION',
					name: 'Duration',
					displayName: 'Duration',
					iconUrl:
						'https://cdn-imgix.headout.com/assets/svg/descriptors/clock.svg',
					description: 'Flexible',
					type: 'STANDARD',
				},
				{
					code: 'SKIP_THE_LINE',
					name: 'Skip the line',
					displayName: 'Skip the line',
					iconUrl:
						'https://cdn-imgix.headout.com/assets/svg/descriptors/skiptheline.svg',
					description: 'Skip the regular queue',
					type: 'STANDARD',
				},
			],
			medias: [
				{
					url: 'https://cdn-imgix.headout.com/media/images/4ff69cd8-caec-4a74-a6a4-4c49735479d8-1750998490160-288155.jpg',
					type: 'IMAGE',
					metadata: {
						altText: 'NYC skyline view combo experience.',
						videoDuration: undefined,
						uploadDate: '2023-10-01',
					},
				},
			],
			listingPrice: {
				currencyCode: 'USD',
				originalPrice: 98.0,
				finalPrice: 74.0,
				minimumPayablePrice: 74.0,
				type: 'PER_PERSON',
				otherPricesExist: false,
				bestDiscount: 24,
				cashbackValue: 0,
				cashbackType: 'PERCENTAGE',
				tourId: 31088,
			},
			primaryCollection: { id: 1101, displayName: 'NYC Combo Deals' },
			primaryCategory: { id: 6, displayName: 'Specials' },
			primarySubCategory: { id: 6001, displayName: 'Combos' },
			primaryCity: { code: 'NEW_YORK', displayName: 'New York' },
			combo: true,
			multiVariant: false,
			flowType: 'NORMAL',
			schedule: undefined,
			personas: [],
			itineraries: [],
			content: undefined,
			minDuration: undefined,
			maxDuration: undefined,
			guestCount: undefined,
			source: undefined,
		},
	],
};
